[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx tsc"

[deploy]
startCommand = "node dist/src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
